# Generated by Django 6.0.1 on 2026-01-31 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smart_farm', '0003_maizevariety_farmdetails_selected_maize_variety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('endpoint', models.CharField(max_length=50)),
                ('requests_made', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='weather_wea_cache_k_466ad6_idx'), models.Index(fields=['expires_at'], name='weather_wea_expires_b662da_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_temp_c', models.FloatField()),
                ('min_temp_c', models.FloatField()),
                ('avg_temp_c', models.FloatField()),
                ('max_wind_kph', models.FloatField()),
                ('total_precip_mm', models.FloatField()),
                ('avg_visibility_km', models.FloatField()),
                ('avg_humidity', models.IntegerField()),
                ('condition', models.CharField(max_length=200)),
                ('hourly_data', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_weather', to='smart_farm.farmdetails')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farm', 'date'], name='weather_his_farm_id_15d134_idx'), models.Index(fields=['date'], name='weather_his_date_74812f_idx')],
                'unique_together': {('farm', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('severity', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('areas', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('certainty', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('effective', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('description', models.TextField()),
                ('instruction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='smart_farm.farmdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'is_active'], name='weather_wea_farm_id_744cb5_idx'), models.Index(fields=['user', 'is_active'], name='weather_wea_user_id_cf2fb0_idx'), models.Index(fields=['severity'], name='weather_wea_severit_7a4326_idx'), models.Index(fields=['expires'], name='weather_wea_expires_34c67a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_temp_c', models.FloatField()),
                ('min_temp_c', models.FloatField()),
                ('avg_temp_c', models.FloatField()),
                ('max_wind_kph', models.FloatField()),
                ('total_precip_mm', models.FloatField()),
                ('avg_visibility_km', models.FloatField()),
                ('avg_humidity', models.IntegerField()),
                ('daily_chance_of_rain', models.IntegerField()),
                ('daily_chance_of_snow', models.IntegerField()),
                ('condition', models.CharField(max_length=200)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('moon_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('moon_illumination', models.CharField(blank=True, max_length=50, null=True)),
                ('air_quality_data', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='smart_farm.farmdetails')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['farm', 'forecast_date'], name='weather_wea_farm_id_b67a83_idx'), models.Index(fields=['forecast_date'], name='weather_wea_forecas_ba9798_idx')],
                'unique_together': {('farm', 'forecast_date')},
            },
        ),
    ]
