# Generated by Django 6.0.1 on 2026-01-31 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soilinformation',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='growingpreferences',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='growingpreferences',
            name='preferred_maize_variety',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='FarmDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(help_text='Name of your farm', max_length=200)),
                ('farm_type', models.CharField(choices=[('smallholder', 'Smallholder'), ('commercial', 'Commercial'), ('subsistence', 'Subsistence'), ('mixed', 'Mixed')], help_text='Type of farming operation', max_length=20)),
                ('farm_size_category', models.CharField(choices=[('less_than_1', 'Less than 1 hectare'), ('1_to_5', '1-5 hectares'), ('5_to_10', '5-10 hectares'), ('10_to_50', '10-50 hectares'), ('more_than_50', 'More than 50 hectares')], help_text='Size of your farm', max_length=20)),
                ('primary_crop', models.CharField(choices=[('maize', 'Maize'), ('cassava', 'Cassava'), ('beans', 'Beans'), ('rice', 'Rice'), ('vegetables', 'Vegetables'), ('mixed', 'Mixed Crops'), ('other', 'Other')], help_text='Main crop grown', max_length=20)),
                ('farming_years', models.IntegerField(help_text='How many years have you been farming?')),
                ('region', models.CharField(choices=[('northwest', 'Northwest'), ('southwest', 'Southwest'), ('west', 'West'), ('littoral', 'Littoral'), ('center', 'Center'), ('east', 'East'), ('adamawa', 'Adamawa'), ('far_north', 'Far North'), ('north', 'North'), ('south', 'South')], help_text='Region where farm is located', max_length=20)),
                ('division', models.CharField(help_text='Division/Department', max_length=100)),
                ('subdivision', models.CharField(help_text='Subdivision/District', max_length=100)),
                ('village_town', models.CharField(help_text='Village or town name', max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, help_text='GPS coordinates (optional)', max_length=100)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('unknown', 'Unknown')], help_text='Type of soil on your farm', max_length=20)),
                ('soil_fertility', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High'), ('unknown', 'Unknown')], help_text='Soil fertility level', max_length=20)),
                ('ph_level', models.FloatField(blank=True, help_text='Soil pH level (if known)', null=True)),
                ('soil_test_done', models.BooleanField(default=False, help_text='Have you done soil testing?')),
                ('last_soil_test_date', models.DateField(blank=True, help_text='Date of last soil test', null=True)),
                ('water_source', models.CharField(choices=[('rain_fed', 'Rain-fed only'), ('well', 'Well'), ('borehole', 'Borehole'), ('river', 'River/Stream'), ('lake', 'Lake'), ('municipal', 'Municipal supply'), ('mixed', 'Mixed sources')], help_text='Main water source', max_length=20)),
                ('irrigation_method', models.CharField(choices=[('none', 'No irrigation'), ('drip', 'Drip irrigation'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood irrigation'), ('manual', 'Manual watering'), ('other', 'Other')], help_text='Irrigation method used', max_length=20)),
                ('water_availability', models.CharField(help_text='Water availability throughout the year', max_length=100)),
                ('irrigation_equipment', models.TextField(blank=True, help_text='Describe irrigation equipment available')),
                ('available_equipment', models.JSONField(default=list, help_text='List of available equipment')),
                ('equipment_details', models.TextField(blank=True, help_text='Additional equipment details')),
                ('labor_source', models.CharField(help_text='Source of labor (family, hired, mixed)', max_length=100)),
                ('labor_count', models.IntegerField(blank=True, help_text='Number of regular workers', null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner - Less than 2 years'), ('intermediate', 'Intermediate - 2-5 years'), ('advanced', 'Advanced - 5-10 years'), ('expert', 'Expert - More than 10 years')], help_text='Farming experience level', max_length=20)),
                ('farming_methods', models.TextField(help_text='Describe your farming methods')),
                ('fertilizer_usage', models.BooleanField(default=True, help_text='Do you use fertilizers?')),
                ('pesticide_usage', models.BooleanField(default=True, help_text='Do you use pesticides?')),
                ('organic_farming', models.BooleanField(default=False, help_text='Do you practice organic farming?')),
                ('farming_goals', models.TextField(help_text='What are your farming goals?')),
                ('main_challenges', models.TextField(help_text='What are your main farming challenges?')),
                ('expected_yield', models.FloatField(blank=True, help_text='Expected yield per hectare (tons)', null=True)),
                ('market_access', models.CharField(help_text='How do you access markets?', max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information')),
                ('phone_number', models.CharField(blank=True, help_text='Alternative contact number', max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether onboarding is completed')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when onboarding was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Details',
                'verbose_name_plural': 'Farm Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='smart_farm.farmdetails'),
        ),
        migrations.DeleteModel(
            name='FarmActivity',
        ),
        migrations.DeleteModel(
            name='SoilInformation',
        ),
        migrations.DeleteModel(
            name='GrowingPreferences',
        ),
        migrations.DeleteModel(
            name='MaizeVariety',
        ),
        migrations.DeleteModel(
            name='OnboardingProgress',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
