# Generated by Django 6.0.1 on 2026-01-31 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0002_remove_farm_user_remove_soilinformation_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaizeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the maize variety', max_length=100)),
                ('code', models.CharField(help_text='Unique code for the variety', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the variety')),
                ('maturity_period', models.CharField(choices=[('early', 'Early (60-80 days)'), ('medium', 'Medium (80-100 days)'), ('late', 'Late (100-120 days)')], help_text='Maturity period', max_length=20)),
                ('expected_yield', models.FloatField(help_text='Expected yield in tons per hectare')),
                ('drought_tolerance', models.BooleanField(default=False, help_text='Drought tolerant variety')),
                ('disease_resistance', models.BooleanField(default=False, help_text='Disease resistant variety')),
                ('recommended_region', models.CharField(blank=True, help_text='Recommended regions for planting', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Image of the variety', null=True, upload_to='maize_varieties/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variety is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maize Variety',
                'verbose_name_plural': 'Maize Varieties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='selected_maize_variety',
            field=models.ForeignKey(blank=True, help_text='Selected maize variety', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_farm.maizevariety'),
        ),
    ]
