# Generated by Django 6.0.1 on 2026-01-31 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0003_maizevariety_farmdetails_selected_maize_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_type', models.CharField(choices=[('smallholder', 'Smallholder'), ('commercial', 'Commercial'), ('subsistence', 'Subsistence'), ('mixed', 'Mixed')], max_length=20)),
                ('farm_size_category', models.CharField(choices=[('less_than_1', 'Less than 1 hectare'), ('1_to_5', '1-5 hectares'), ('5_to_10', '5-10 hectares'), ('10_to_50', '10-50 hectares'), ('more_than_50', 'More than 50 hectares')], max_length=20)),
                ('primary_crop', models.CharField(choices=[('maize', 'Maize'), ('cassava', 'Cassava'), ('beans', 'Beans'), ('rice', 'Rice'), ('vegetables', 'Vegetables'), ('mixed', 'Mixed Crops'), ('other', 'Other')], max_length=20)),
                ('farming_years', models.IntegerField()),
                ('region', models.CharField(choices=[('northwest', 'Northwest'), ('southwest', 'Southwest'), ('west', 'West'), ('littoral', 'Littoral'), ('center', 'Center'), ('east', 'East'), ('adamawa', 'Adamawa'), ('far_north', 'Far North'), ('north', 'North'), ('south', 'South')], max_length=20)),
                ('division', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=100)),
                ('village_town', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farms',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('planting', 'Planting'), ('harvesting', 'Harvesting'), ('fertilizing', 'Fertilizing'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('weeding', 'Weeding'), ('observation', 'Observation'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='smart_farm.farm')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
