# Generated by Django 6.0.1 on 2026-01-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0004_farm_farmactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmactivity',
            name='farm',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='FarmActivity',
        ),
    ]
