# Generated by Django 6.0.1 on 2026-01-31 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0005_remove_farmactivity_farm_delete_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
