# Generated by Django 6.0.2 on 2026-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0006_alter_farmdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
