# Generated by Django 6.0.2 on 2026-02-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm', '0007_remove_redundant_user_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
